### ISSUE TITLE
move all non-notebook .py with command line interfaces to the dmsbatch source directory

### ISSUE THREAD

**Issue by dwr-psandhu** [CADWRDeltaModeling/azure_dms_batch#5]
I noticed that the ptm batch submission files are in the notebooks folder. That folder is only for examples or tests.
These should be moved to dmsbatch so that they are available there and consolidate them under dmsbatch subcommands.

**Comment by fishatbdo** [comment]
will move them to dmsbatch.

**Comment by fishatbdo** [comment]
done the move.  Please close the issue.
